package fi.muni.redhat.hiperex.model;
import fi.muni.redhat.hiperex.model.CustomerOrder;
import fi.muni.redhat.hiperex.model.ItemListId;
import fi.muni.redhat.hiperex.model.Product;

// default package
// Generated Dec 25, 2012 6:41:35 PM by Hibernate Tools 4.0.0

/**
 * ItemList generated by hbm2java
 */
public class ItemList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -968355992915059537L;
	private ItemListId id;
	private Product product;
	private CustomerOrder customerOrder;
	private Integer quantity;

	public ItemList() {
	}

	public ItemList(ItemListId id, Product product, CustomerOrder customerOrder) {
		this.id = id;
		this.product = product;
		this.customerOrder = customerOrder;
	}

	public ItemList(ItemListId id, Product product, CustomerOrder customerOrder, Integer quantity) {
		this.id = id;
		this.product = product;
		this.customerOrder = customerOrder;
		this.quantity = quantity;
	}

	public ItemListId getId() {
		return this.id;
	}

	public void setId(ItemListId id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public CustomerOrder getCustomerOrder() {
		return this.customerOrder;
	}

	public void setCustomerOrder(CustomerOrder customerOrder) {
		this.customerOrder = customerOrder;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
