package fi.muni.redhat.hiperex.model;

// Generated Dec 25, 2012 6:01:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5793087607000563637L;
	private int productId;
	private String name;
	private Set<ItemList> itemLists = new HashSet<ItemList>(0);

	public Product() {
	}

	public Product(int productId) {
		this.productId = productId;
	}

	public Product(int productId, String name, Set<ItemList> itemLists) {
		this.productId = productId;
		this.name = name;
		this.itemLists = itemLists;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<ItemList> getItemLists() {
		return this.itemLists;
	}

	public void setItemLists(Set<ItemList> itemLists) {
		this.itemLists = itemLists;
	}

}
