package fi.muni.redhat.hiperex.model;

// Generated Dec 25, 2012 6:01:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int productId;
	private String name;
	private Set itemLists = new HashSet(0);

	public Product() {
	}

	public Product(int productId) {
		this.productId = productId;
	}

	public Product(int productId, String name, Set itemLists) {
		this.productId = productId;
		this.name = name;
		this.itemLists = itemLists;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItemLists() {
		return this.itemLists;
	}

	public void setItemLists(Set itemLists) {
		this.itemLists = itemLists;
	}

}
